### ISSUE TITLE
(Proposal) Remove `lastItemPlayed` from `GET /library`

### ISSUE THREAD

**Issue by harrisi** [TortugaPower/bookplayer-api#5]
Since `lastItemPlayed` can be got from `GET /library/last_played`, including it in `GET /library` mostly means that just a single sync in any folder causes `GET /library` to become stale, forcing a new version to be sent even though the root contents may be the same. I propose removing the `lastItemPlayed` from the `/library` GET response to reduce data usage. This is also related to #3.

**Comment by ynunezaguirre** [comment]
Thanks @harrisi, your pr with the fix is merged.
